# Generated by Django 4.0 on 2021-12-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('meta', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('meta', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('values', models.JSONField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('Variantsframeworkid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.group')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_types',
        ),
        migrations.RemoveField(
            model_name='bookprice',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookprice',
            name='book_type',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookPrice',
        ),
        migrations.DeleteModel(
            name='BookType',
        ),
    ]
